name: Build Setup Scripts (tagged release)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure tag is on main
        run: |
          DEFAULT_BRANCH="main"
          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
          BRANCH_COMMIT=$(git rev-parse origin/$DEFAULT_BRANCH)

          if [ "$TAG_COMMIT" != "$BRANCH_COMMIT" ]; then
              echo "Tag does not point to the latest commit on '$DEFAULT_BRANCH'."
              echo "Please ensure you're tagging the tip of the main branch."
              exit 1
          fi

      - name: Record version
        run: echo "${GITHUB_REF##*/}" > VERSION

      - name: Build all recipes
        run: |
          mkdir -p dist
          for recipe in recipes/*.recipe; do
            bash builder/build.bash "$recipe" > "dist/$(basename "${recipe%.recipe}.bash")"
          done
          cp VERSION dist/VERSION

      - name: Create GitHub release for tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Setup Scripts ${{ github.ref_name }}
          files: dist/*
